source: ./source
# destination: /mnt/c/Users/karlw/Sites/drawshield.net
destination: /home/karl/Sites/drawshield.home


# Directory
include: [ .htaccess ]

defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"

siteURL: https://drawshield.net
siteTitle: DrawShield

buildNum: 578

latestGallery: 9185
incrementGallery: 20

collections:
  catalog:
    output: true
  reference:
    output: true
