source: ./source
destination: /mnt/e/Sites/drawshield.home
# destination: /home/karlw/Sites/drawshield.home


# Directory
include: [ .htaccess ]

defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"

siteURL: https://drawshield.net
siteTitle: DrawShield

buildNum: 710

latestGallery: 8430
incrementGallery: 20

collections:
  catalog:
    output: true
  reference:
    output: true
  gplus:
    output: true

