source: ./source
# destination: /mnt/c/Users/karlw/Sites/drawshield.net
destination: /home/karl/Sites/drawshield.home


# Directory
include: [ .htaccess ]

defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"

siteURL: https://drawshield.net
siteTitle: DrawShield

buildNum: 683

latestGallery: 8527
incrementGallery: 20

collections:
  catalog:
    output: false
  reference:
    output: false
  gplus:
    output: false

