source: ./source
# Command line destination can override this
destination: /var/www/test
# destination: /home/karlw/Sites/drawshield.home


# don't delete
keep_files: [ .htaccess, include, gallery/giotd.html ]

defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"

siteURL: https://drawshield.net
siteTitle: DrawShield

buildNum: 879

latestGallery: 6565
incrementGallery: 20

collections:
  catalog:
    output: true
  reference:
    output: false
  gplus:
    output: false

