source: ./source
# give destination on command line
# destination: /var/www/html
# destination: /home/karlw/Sites/drawshield.home


# don't delete
keep_files: [ .htaccess, include ]

defaults:
    -
      scope:
        path: ""
      values:
        layout: "default"

siteURL: https://drawshield.net
siteTitle: DrawShield

buildNum: 714

latestGallery: 8384
incrementGallery: 20

collections:
  catalog:
    output: true
  reference:
    output: false
  gplus:
    output: false

